[server]
headless = true

[theme]
primaryColor = "#DA291C"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1A1A2E"
textColor = "#FFFFFF"
font = "sans serif"

[browser]
gatherUsageStats = false
